// ------------------------------------------------------------------------------
//  <auto-generated>
//      Этот код был создан построителем кодированных тестов ИП.
//      Версия: 15.0.0.0
//
//      Изменения, внесенные в этот файл, могут привести к неправильной работе кода и будут
//      утрачены при повторном формировании кода.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// ExecMethod - Используйте "ExecMethodParams" для передачи параметров в этот метод.
        /// </summary>
        public void ExecMethod()
        {
            #region Variable Declarations
            WinEdit uINum1Edit = this.UIЛабораторнаяработа1Window.UINum1Window.UINum1Edit;
            WinEdit uINum2Edit = this.UIЛабораторнаяработа1Window.UINum2Window.UINum2Edit;
            WinEdit uINum3Edit = this.UIЛабораторнаяработа1Window.UINum3Window.UINum3Edit;
            WinEdit uINum4Edit = this.UIЛабораторнаяработа1Window.UINum4Window.UINum4Edit;
            WinEdit uINum5Edit = this.UIЛабораторнаяработа1Window.UINum5Window.UINum5Edit;
            WinEdit uINum10Edit = this.UIЛабораторнаяработа1Window.UINum10Window.UINum10Edit;
            WinEdit uINum9Edit = this.UIЛабораторнаяработа1Window.UINum9Window.UINum9Edit;
            WinEdit uINum6Edit = this.UIЛабораторнаяработа1Window.UINum6Window.UINum6Edit;
            WinEdit uINum7Edit = this.UIЛабораторнаяработа1Window.UINum7Window.UINum7Edit;
            WinEdit uINum8Edit = this.UIЛабораторнаяработа1Window.UINum8Window.UINum8Edit;
            WinButton uIВыполнитьButton = this.UIЛабораторнаяработа1Window.UIВыполнитьWindow.UIВыполнитьButton;
            #endregion

            // Запуск "%USERPROFILE%\Desktop\lab1-3.exe"
            ApplicationUnderTest lab13Application = ApplicationUnderTest.Launch(this.ExecMethodParams.ExePath, this.ExecMethodParams.AlternateExePath);

            // Тип "1111" в "num1" надпись
            uINum1Edit.Text = this.ExecMethodParams.UINum1EditText;

            // Тип "1234" в "num2" надпись
            uINum2Edit.Text = this.ExecMethodParams.UINum2EditText;

            // Тип "1237" в "num3" надпись
            uINum3Edit.Text = this.ExecMethodParams.UINum3EditText;

            // Тип "1277" в "num4" надпись
            uINum4Edit.Text = this.ExecMethodParams.UINum4EditText;

            // Тип "1777" в "num5" надпись
            uINum5Edit.Text = this.ExecMethodParams.UINum5EditText;

            // Тип "7777" в "num10" надпись
            uINum10Edit.Text = this.ExecMethodParams.UINum10EditText;

            // Тип "7778" в "num9" надпись
            uINum9Edit.Text = this.ExecMethodParams.UINum9EditText;

            // Тип "1239" в "num6" надпись
            uINum6Edit.Text = this.ExecMethodParams.UINum6EditText;

            // Тип "1297" в "num7" надпись
            uINum7Edit.Text = this.ExecMethodParams.UINum7EditText;

            // Тип "8888" в "num8" надпись
            uINum8Edit.Text = this.ExecMethodParams.UINum8EditText;

            // Щелкните "Выполнить" кнопка
            Mouse.Click(uIВыполнитьButton, new Point(37, 15));
        }
        
        /// <summary>
        /// AssertMethod - Используйте "AssertMethodExpectedValues" для передачи параметров в этот метод.
        /// </summary>
        public void AssertMethod()
        {
            #region Variable Declarations
            WinEdit uIResultEdit = this.UIЛабораторнаяработа1Window.UIResultWindow.UIResultEdit;
            #endregion

            // Убедитесь, что свойство Text "result" надпись равняется "3"
            Assert.AreEqual(this.AssertMethodExpectedValues.UIResultEditText, uIResultEdit.Text);
        }
        
        /// <summary>
        /// ExitingMethod
        /// </summary>
        public void ExitingMethod()
        {
            #region Variable Declarations
            WinButton uIВыходButton = this.UIЛабораторнаяработа1Window.UIВыходWindow.UIВыходButton;
            #endregion

            // Щелкните "Выход" кнопка
            Mouse.Click(uIВыходButton, new Point(39, 5));
        }
        
        #region Properties
        public virtual ExecMethodParams ExecMethodParams
        {
            get
            {
                if ((this.mExecMethodParams == null))
                {
                    this.mExecMethodParams = new ExecMethodParams();
                }
                return this.mExecMethodParams;
            }
        }
        
        public virtual AssertMethodExpectedValues AssertMethodExpectedValues
        {
            get
            {
                if ((this.mAssertMethodExpectedValues == null))
                {
                    this.mAssertMethodExpectedValues = new AssertMethodExpectedValues();
                }
                return this.mAssertMethodExpectedValues;
            }
        }
        
        public UIЛабораторнаяработа1Window UIЛабораторнаяработа1Window
        {
            get
            {
                if ((this.mUIЛабораторнаяработа1Window == null))
                {
                    this.mUIЛабораторнаяработа1Window = new UIЛабораторнаяработа1Window();
                }
                return this.mUIЛабораторнаяработа1Window;
            }
        }
        #endregion
        
        #region Fields
        private ExecMethodParams mExecMethodParams;
        
        private AssertMethodExpectedValues mAssertMethodExpectedValues;
        
        private UIЛабораторнаяработа1Window mUIЛабораторнаяработа1Window;
        #endregion
    }
    
    /// <summary>
    /// Параметры для передачи в "ExecMethod"
    /// </summary>
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class ExecMethodParams
    {
        
        #region Fields
        /// <summary>
        /// Запуск "%USERPROFILE%\Desktop\lab1-3.exe"
        /// </summary>
        public string ExePath = "C:\\Users\\maxix\\Desktop\\lab1-3.exe";
        
        /// <summary>
        /// Запуск "%USERPROFILE%\Desktop\lab1-3.exe"
        /// </summary>
        public string AlternateExePath = "%USERPROFILE%\\Desktop\\lab1-3.exe";
        
        /// <summary>
        /// Тип "1111" в "num1" надпись
        /// </summary>
        public string UINum1EditText = "1111";
        
        /// <summary>
        /// Тип "1234" в "num2" надпись
        /// </summary>
        public string UINum2EditText = "1234";
        
        /// <summary>
        /// Тип "1237" в "num3" надпись
        /// </summary>
        public string UINum3EditText = "1237";
        
        /// <summary>
        /// Тип "1277" в "num4" надпись
        /// </summary>
        public string UINum4EditText = "1277";
        
        /// <summary>
        /// Тип "1777" в "num5" надпись
        /// </summary>
        public string UINum5EditText = "1777";
        
        /// <summary>
        /// Тип "7777" в "num10" надпись
        /// </summary>
        public string UINum10EditText = "7777";
        
        /// <summary>
        /// Тип "7778" в "num9" надпись
        /// </summary>
        public string UINum9EditText = "7778";
        
        /// <summary>
        /// Тип "1239" в "num6" надпись
        /// </summary>
        public string UINum6EditText = "1239";
        
        /// <summary>
        /// Тип "1297" в "num7" надпись
        /// </summary>
        public string UINum7EditText = "1297";
        
        /// <summary>
        /// Тип "8888" в "num8" надпись
        /// </summary>
        public string UINum8EditText = "8888";
        #endregion
    }
    
    /// <summary>
    /// Параметры для передачи в "AssertMethod"
    /// </summary>
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class AssertMethodExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Убедитесь, что свойство Text "result" надпись равняется "3"
        /// </summary>
        public string UIResultEditText = "3";
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UIЛабораторнаяработа1Window : WinWindow
    {
        
        public UIЛабораторнаяработа1Window()
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Лабораторная работа №1";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Лабораторная работа №1");
            #endregion
        }
        
        #region Properties
        public UINum1Window UINum1Window
        {
            get
            {
                if ((this.mUINum1Window == null))
                {
                    this.mUINum1Window = new UINum1Window(this);
                }
                return this.mUINum1Window;
            }
        }
        
        public UINum2Window UINum2Window
        {
            get
            {
                if ((this.mUINum2Window == null))
                {
                    this.mUINum2Window = new UINum2Window(this);
                }
                return this.mUINum2Window;
            }
        }
        
        public UINum3Window UINum3Window
        {
            get
            {
                if ((this.mUINum3Window == null))
                {
                    this.mUINum3Window = new UINum3Window(this);
                }
                return this.mUINum3Window;
            }
        }
        
        public UINum4Window UINum4Window
        {
            get
            {
                if ((this.mUINum4Window == null))
                {
                    this.mUINum4Window = new UINum4Window(this);
                }
                return this.mUINum4Window;
            }
        }
        
        public UINum5Window UINum5Window
        {
            get
            {
                if ((this.mUINum5Window == null))
                {
                    this.mUINum5Window = new UINum5Window(this);
                }
                return this.mUINum5Window;
            }
        }
        
        public UINum10Window UINum10Window
        {
            get
            {
                if ((this.mUINum10Window == null))
                {
                    this.mUINum10Window = new UINum10Window(this);
                }
                return this.mUINum10Window;
            }
        }
        
        public UINum9Window UINum9Window
        {
            get
            {
                if ((this.mUINum9Window == null))
                {
                    this.mUINum9Window = new UINum9Window(this);
                }
                return this.mUINum9Window;
            }
        }
        
        public UINum6Window UINum6Window
        {
            get
            {
                if ((this.mUINum6Window == null))
                {
                    this.mUINum6Window = new UINum6Window(this);
                }
                return this.mUINum6Window;
            }
        }
        
        public UINum7Window UINum7Window
        {
            get
            {
                if ((this.mUINum7Window == null))
                {
                    this.mUINum7Window = new UINum7Window(this);
                }
                return this.mUINum7Window;
            }
        }
        
        public UINum8Window UINum8Window
        {
            get
            {
                if ((this.mUINum8Window == null))
                {
                    this.mUINum8Window = new UINum8Window(this);
                }
                return this.mUINum8Window;
            }
        }
        
        public UIВыполнитьWindow UIВыполнитьWindow
        {
            get
            {
                if ((this.mUIВыполнитьWindow == null))
                {
                    this.mUIВыполнитьWindow = new UIВыполнитьWindow(this);
                }
                return this.mUIВыполнитьWindow;
            }
        }
        
        public UIResultWindow UIResultWindow
        {
            get
            {
                if ((this.mUIResultWindow == null))
                {
                    this.mUIResultWindow = new UIResultWindow(this);
                }
                return this.mUIResultWindow;
            }
        }
        
        public UIВыходWindow UIВыходWindow
        {
            get
            {
                if ((this.mUIВыходWindow == null))
                {
                    this.mUIВыходWindow = new UIВыходWindow(this);
                }
                return this.mUIВыходWindow;
            }
        }
        #endregion
        
        #region Fields
        private UINum1Window mUINum1Window;
        
        private UINum2Window mUINum2Window;
        
        private UINum3Window mUINum3Window;
        
        private UINum4Window mUINum4Window;
        
        private UINum5Window mUINum5Window;
        
        private UINum10Window mUINum10Window;
        
        private UINum9Window mUINum9Window;
        
        private UINum6Window mUINum6Window;
        
        private UINum7Window mUINum7Window;
        
        private UINum8Window mUINum8Window;
        
        private UIВыполнитьWindow mUIВыполнитьWindow;
        
        private UIResultWindow mUIResultWindow;
        
        private UIВыходWindow mUIВыходWindow;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UINum1Window : WinWindow
    {
        
        public UINum1Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "num1";
            this.WindowTitles.Add("Лабораторная работа №1");
            #endregion
        }
        
        #region Properties
        public WinEdit UINum1Edit
        {
            get
            {
                if ((this.mUINum1Edit == null))
                {
                    this.mUINum1Edit = new WinEdit(this);
                    #region Условия поиска
                    this.mUINum1Edit.WindowTitles.Add("Лабораторная работа №1");
                    #endregion
                }
                return this.mUINum1Edit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUINum1Edit;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UINum2Window : WinWindow
    {
        
        public UINum2Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "num2";
            this.WindowTitles.Add("Лабораторная работа №1");
            #endregion
        }
        
        #region Properties
        public WinEdit UINum2Edit
        {
            get
            {
                if ((this.mUINum2Edit == null))
                {
                    this.mUINum2Edit = new WinEdit(this);
                    #region Условия поиска
                    this.mUINum2Edit.WindowTitles.Add("Лабораторная работа №1");
                    #endregion
                }
                return this.mUINum2Edit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUINum2Edit;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UINum3Window : WinWindow
    {
        
        public UINum3Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "num3";
            this.WindowTitles.Add("Лабораторная работа №1");
            #endregion
        }
        
        #region Properties
        public WinEdit UINum3Edit
        {
            get
            {
                if ((this.mUINum3Edit == null))
                {
                    this.mUINum3Edit = new WinEdit(this);
                    #region Условия поиска
                    this.mUINum3Edit.WindowTitles.Add("Лабораторная работа №1");
                    #endregion
                }
                return this.mUINum3Edit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUINum3Edit;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UINum4Window : WinWindow
    {
        
        public UINum4Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "num4";
            this.WindowTitles.Add("Лабораторная работа №1");
            #endregion
        }
        
        #region Properties
        public WinEdit UINum4Edit
        {
            get
            {
                if ((this.mUINum4Edit == null))
                {
                    this.mUINum4Edit = new WinEdit(this);
                    #region Условия поиска
                    this.mUINum4Edit.WindowTitles.Add("Лабораторная работа №1");
                    #endregion
                }
                return this.mUINum4Edit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUINum4Edit;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UINum5Window : WinWindow
    {
        
        public UINum5Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "num5";
            this.WindowTitles.Add("Лабораторная работа №1");
            #endregion
        }
        
        #region Properties
        public WinEdit UINum5Edit
        {
            get
            {
                if ((this.mUINum5Edit == null))
                {
                    this.mUINum5Edit = new WinEdit(this);
                    #region Условия поиска
                    this.mUINum5Edit.WindowTitles.Add("Лабораторная работа №1");
                    #endregion
                }
                return this.mUINum5Edit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUINum5Edit;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UINum10Window : WinWindow
    {
        
        public UINum10Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "num10";
            this.WindowTitles.Add("Лабораторная работа №1");
            #endregion
        }
        
        #region Properties
        public WinEdit UINum10Edit
        {
            get
            {
                if ((this.mUINum10Edit == null))
                {
                    this.mUINum10Edit = new WinEdit(this);
                    #region Условия поиска
                    this.mUINum10Edit.WindowTitles.Add("Лабораторная работа №1");
                    #endregion
                }
                return this.mUINum10Edit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUINum10Edit;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UINum9Window : WinWindow
    {
        
        public UINum9Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "num9";
            this.WindowTitles.Add("Лабораторная работа №1");
            #endregion
        }
        
        #region Properties
        public WinEdit UINum9Edit
        {
            get
            {
                if ((this.mUINum9Edit == null))
                {
                    this.mUINum9Edit = new WinEdit(this);
                    #region Условия поиска
                    this.mUINum9Edit.WindowTitles.Add("Лабораторная работа №1");
                    #endregion
                }
                return this.mUINum9Edit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUINum9Edit;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UINum6Window : WinWindow
    {
        
        public UINum6Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "num6";
            this.WindowTitles.Add("Лабораторная работа №1");
            #endregion
        }
        
        #region Properties
        public WinEdit UINum6Edit
        {
            get
            {
                if ((this.mUINum6Edit == null))
                {
                    this.mUINum6Edit = new WinEdit(this);
                    #region Условия поиска
                    this.mUINum6Edit.WindowTitles.Add("Лабораторная работа №1");
                    #endregion
                }
                return this.mUINum6Edit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUINum6Edit;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UINum7Window : WinWindow
    {
        
        public UINum7Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "num7";
            this.WindowTitles.Add("Лабораторная работа №1");
            #endregion
        }
        
        #region Properties
        public WinEdit UINum7Edit
        {
            get
            {
                if ((this.mUINum7Edit == null))
                {
                    this.mUINum7Edit = new WinEdit(this);
                    #region Условия поиска
                    this.mUINum7Edit.WindowTitles.Add("Лабораторная работа №1");
                    #endregion
                }
                return this.mUINum7Edit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUINum7Edit;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UINum8Window : WinWindow
    {
        
        public UINum8Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "num8";
            this.WindowTitles.Add("Лабораторная работа №1");
            #endregion
        }
        
        #region Properties
        public WinEdit UINum8Edit
        {
            get
            {
                if ((this.mUINum8Edit == null))
                {
                    this.mUINum8Edit = new WinEdit(this);
                    #region Условия поиска
                    this.mUINum8Edit.WindowTitles.Add("Лабораторная работа №1");
                    #endregion
                }
                return this.mUINum8Edit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUINum8Edit;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UIВыполнитьWindow : WinWindow
    {
        
        public UIВыполнитьWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "execButton";
            this.WindowTitles.Add("Лабораторная работа №1");
            #endregion
        }
        
        #region Properties
        public WinButton UIВыполнитьButton
        {
            get
            {
                if ((this.mUIВыполнитьButton == null))
                {
                    this.mUIВыполнитьButton = new WinButton(this);
                    #region Условия поиска
                    this.mUIВыполнитьButton.SearchProperties[WinButton.PropertyNames.Name] = "Выполнить";
                    this.mUIВыполнитьButton.WindowTitles.Add("Лабораторная работа №1");
                    #endregion
                }
                return this.mUIВыполнитьButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIВыполнитьButton;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UIResultWindow : WinWindow
    {
        
        public UIResultWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "result";
            this.WindowTitles.Add("Лабораторная работа №1");
            #endregion
        }
        
        #region Properties
        public WinEdit UIResultEdit
        {
            get
            {
                if ((this.mUIResultEdit == null))
                {
                    this.mUIResultEdit = new WinEdit(this);
                    #region Условия поиска
                    this.mUIResultEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Количество чисел, сумма цифр которых кратна 7 и их среднее арифметическое меньше " +
                        "7";
                    this.mUIResultEdit.WindowTitles.Add("Лабораторная работа №1");
                    #endregion
                }
                return this.mUIResultEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIResultEdit;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UIВыходWindow : WinWindow
    {
        
        public UIВыходWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "exitButton";
            this.WindowTitles.Add("Лабораторная работа №1");
            #endregion
        }
        
        #region Properties
        public WinButton UIВыходButton
        {
            get
            {
                if ((this.mUIВыходButton == null))
                {
                    this.mUIВыходButton = new WinButton(this);
                    #region Условия поиска
                    this.mUIВыходButton.SearchProperties[WinButton.PropertyNames.Name] = "Выход";
                    this.mUIВыходButton.WindowTitles.Add("Лабораторная работа №1");
                    #endregion
                }
                return this.mUIВыходButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIВыходButton;
        #endregion
    }
}
